/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    App: typeof import('./src/components/ProLayout/examples/App.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BasicLayout: typeof import('./src/components/ProLayout/examples/layouts/BasicLayout.vue')['default']
    BlankLayout: typeof import('./src/components/ProLayout/examples/layouts/BlankLayout.vue')['default']
    CheckOutlined: typeof import('@ant-design/icons-vue')['CheckOutlined']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    DynamicPage: typeof import('./src/components/ProLayout/examples/views/DynamicPage.vue')['default']
    Hello: typeof import('./src/components/ProLayout/examples/views/Hello.vue')['default']
    MyPage: typeof import('./src/components/ProLayout/examples/views/MyPage.vue')['default']
    NestedLayout: typeof import('./src/components/ProLayout/examples/layouts/NestedLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectModelDialog: typeof import('./src/components/SelectModelDialog/index.vue')['default']
    SettingDrawer: typeof import('./src/components/SettingDrawer/SettingDrawer.vue')['default']
    SettingItem: typeof import('./src/components/SettingDrawer/SettingItem.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TestPage: typeof import('./src/components/ProLayout/examples/views/TestPage.vue')['default']
    TestTab: typeof import('./src/components/ProLayout/examples/views/TestTab.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
